# wrangler.toml  ← place this at project root (same level as package.json)
name = "jottosop"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"
NEXT_PUBLIC_API_URL = "https://seller-side-backend-fastify-nest.onrender.com"