# wrangler.toml  ← place this at project root (same level as package.json)
name = "jottosop"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
NEXT_PUBLIC_GA_ID = "d7orZYINZTDOwtx5kOP_6XZXhLg-uv1Ht3fG_s9WuBA"
NEXT_PUBLIC_SITE_URL = "https://jottosop.in"

[secrets]
NEXT_PUBLIC_API_URL = "https://seller-side-backend-fastify-nest.onrender.com"
NEXT_PUBLIC_RAZORPAY_KEY_ID = "rzp_live_SQmvUZPpN5MS3L"
NEXT_PUBLIC_GOOGLE_CLIENT_ID = "939883123761-up76q4mal36sd3quh558ssccr1cqc035.apps.googleusercontent.com"