import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./store/Provider";
import Navbar from "./components/Navbar";
import { Toaster } from "react-hot-toast"; // 1. Import the Toaster component
import Footer from "./components/Footer";
import Script from "next/script";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Jottosop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <Toaster /> 
          <Navbar/>
        {children}
        </Providers>
        <Footer/>
      </body>
          <Script src="https://checkout.razorpay.com/v1/checkout.js"/>
    </html>
  );
}
